books=eval(input("Enter books list : "))
add_val=input("Add to the list : ")
remove_val=input("Remove from the list : ")
books.insert(len(books),add_val)
books.remove(remove_val)
print("Books = ",books)
